"""Seed humanities and social-sciences resources into the database.

This script is idempotent: existing resources are skipped based on their id.
Run it after migrations/admin creation to populate a richer catalog.

Example:
    cd backend
    .venv/bin/python scripts/seed_resources.py
"""

from __future__ import annotations

import asyncio

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import async_session, engine
from app.models.models import Base, Resource


SEED_DATA: list[dict] = [
    {
        "id": 'deep-learning-goodfellow-2016',
        "type": 'book',
        "title": 'Deep Learning',
        "authors": ['Ian Goodfellow', 'Yoshua Bengio', 'Aaron Courville'],
        "year": 2016,
        "venue": 'MIT Press',
        "discipline": 'computer-science',
        "subdiscipline": 'machine-learning',
        "tags": ['深度学习', 'deep learning', '神经网络', 'textbook'],
        "abstract": '《Deep Learning》是 MIT Press 于 2016 年出版的深度学习领域经典教材，系统介绍了机器学习与深度学习所需的数学基础、经典模型与前沿进展。',
        "preview": 'MIT Press 2016 年出版的深度学习经典教材，涵盖数学基础、经典模型与前沿进展。',
        "download_url": 'https://github.com/ms33834/scholarhub/raw/main/assets/books/deep-learning-2016.pdf',
        "external_url": 'https://www.deeplearningbook.org/',
        "doi": None,
        "citation": {
            "apa": 'Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.',
            "mla": 'Goodfellow, Ian, Yoshua Bengio, and Aaron Courville. Deep Learning. MIT Press, 2016.',
            "gbt": 'Goodfellow I, Bengio Y, Courville A. Deep Learning[M]. MIT Press, 2016.',
            "bibtex": '@book{goodfellow2016deep, title={Deep Learning}, author={Goodfellow, Ian and Bengio, Yoshua and Courville, Aaron}, year={2016}, publisher={MIT Press}}',
        },
        "citations": 52000,
        "added_at": '2026-06-11',
    },
    {
        "id": 'attention-is-all-you-need-2017',
        "type": 'paper',
        "title": 'Attention Is All You Need',
        "authors": ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit', 'Llion Jones', 'Aidan N. Gomez', 'Lukasz Kaiser', 'Illia Polosukhin'],
        "year": 2017,
        "venue": 'Advances in Neural Information Processing Systems 30 (NeurIPS 2017)',
        "discipline": 'computer-science',
        "subdiscipline": 'natural-language-processing',
        "tags": ['Transformer', '注意力机制', 'NLP', '深度学习'],
        "abstract": '本文提出了 Transformer，一种完全基于注意力机制的序列转换模型，摒弃了循环与卷积结构，在机器翻译任务上取得了优异效果并启发了后续大量预训练语言模型。',
        "preview": '提出 Transformer 架构，完全基于注意力机制，成为现代 NLP 与大语言模型的基石。',
        "download_url": 'https://arxiv.org/pdf/1706.03762.pdf',
        "external_url": 'https://arxiv.org/abs/1706.03762',
        "doi": None,
        "citation": {
            "apa": 'Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A. N., Kaiser, L., & Polosukhin, I. (2017). Attention is all you need. Advances in Neural Information Processing Systems, 30.',
            "mla": 'Vaswani, Ashish, et al. "Attention is all you need." Advances in Neural Information Processing Systems, vol. 30, 2017.',
            "gbt": 'Vaswani A, Shazeer N, Parmar N, et al. Attention is all you need[C]//Advances in Neural Information Processing Systems. 2017, 30.',
            "bibtex": '@inproceedings{vaswani2017attention, title={Attention is all you need}, author={Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, {\\L}ukasz and Polosukhin, Illia}, booktitle={Advances in Neural Information Processing Systems}, volume={30}, year={2017}}',
        },
        "citations": 89000,
        "added_at": '2026-06-11',
    },
    {
        "id": 'imagenet-deng-2009',
        "type": 'dataset',
        "title": 'ImageNet: A Large-Scale Hierarchical Image Database',
        "authors": ['Jia Deng', 'Wei Dong', 'Richard Socher', 'Li-Jia Li', 'Kai Li', 'Li Fei-Fei'],
        "year": 2009,
        "venue": 'CVPR 2009',
        "discipline": 'computer-science',
        "subdiscipline": 'computer-vision',
        "tags": ['计算机视觉', '数据集', 'ImageNet', '图像分类'],
        "abstract": 'ImageNet 是一个大规模层次化图像数据库，包含数万个类别与上千万张图像，极大推动了视觉识别与深度学习的发展。',
        "preview": '大规模层次化图像数据库，推动深度学习在计算机视觉领域的发展。',
        "download_url": 'https://www.image-net.org/download.php',
        "external_url": 'https://www.image-net.org/',
        "doi": None,
        "citation": {
            "apa": 'Deng, J., Dong, W., Socher, R., Li, L. J., Li, K., & Fei-Fei, L. (2009). ImageNet: A large-scale hierarchical image database. IEEE Conference on Computer Vision and Pattern Recognition.',
            "mla": 'Deng, Jia, et al. "ImageNet: A large-scale hierarchical image database." IEEE Conference on Computer Vision and Pattern Recognition, 2009.',
            "gbt": 'Deng J, Dong W, Socher R, et al. ImageNet: A large-scale hierarchical image database[C]//IEEE Conference on Computer Vision and Pattern Recognition. 2009.',
            "bibtex": '@inproceedings{deng2009imagenet, title={ImageNet: A Large-Scale Hierarchical Image Database}, author={Deng, Jia and Dong, Wei and Socher, Richard and Li, Li-Jia and Li, Kai and Fei-Fei, Li}, booktitle={IEEE Conference on Computer Vision and Pattern Recognition}, year={2009}}',
        },
        "citations": 78000,
        "added_at": '2026-06-12',
    },
    {
        "id": 'cs229-machine-learning-notes',
        "type": 'tutorial',
        "title": 'CS229 Machine Learning Course Notes',
        "authors": ['Andrew Ng'],
        "year": 2021,
        "venue": 'Stanford CS229',
        "discipline": 'computer-science',
        "subdiscipline": 'machine-learning',
        "tags": ['机器学习', '课程笔记', 'Stanford', '入门'],
        "abstract": '斯坦福大学 CS229 机器学习课程官方笔记，系统讲解监督学习、非监督学习、深度学习基础与强化学习入门。',
        "preview": 'Stanford CS229 官方课程笔记，系统覆盖监督学习、非监督学习与深度学习基础。',
        "download_url": 'https://cs229.stanford.edu/notes2021fall/deeplearning-notes.pdf',
        "external_url": 'https://cs229.stanford.edu/',
        "doi": None,
        "citation": {
            "apa": 'Ng, A. (2021). CS229 Machine Learning course notes. Stanford University.',
            "mla": 'Ng, Andrew. CS229 Machine Learning Course Notes. Stanford University, 2021.',
            "gbt": 'Ng A. CS229 Machine Learning course notes[EB/OL]. Stanford University, 2021.',
            "bibtex": '@misc{ng2021cs229, title={CS229 Machine Learning course notes}, author={Ng, Andrew}, year={2021}, howpublished={\\url{https://cs229.stanford.edu/}}}',
        },
        "citations": 1200,
        "added_at": '2026-06-12',
    },
    {
        "id": 'linear-algebra-done-right-axler-2015',
        "type": 'book',
        "title": 'Linear Algebra Done Right',
        "authors": ['Sheldon Axler'],
        "year": 2015,
        "venue": 'Springer',
        "discipline": 'mathematics',
        "subdiscipline": 'linear-algebra',
        "tags": ['线性代数', '数学', '教材', '入门'],
        "abstract": '《Linear Algebra Done Right》是一本著名的线性代数教材，从向量空间与线性映射的角度出发，避免直接使用行列式来引入核心概念。',
        "preview": '著名线性代数教材，从向量空间视角出发，适合数学与理工科学生入门。',
        "download_url": None,
        "external_url": 'https://linear.axler.net/',
        "doi": '10.1007/978-3-319-11080-6',
        "citation": {
            "apa": 'Axler, S. (2015). Linear algebra done right (3rd ed.). Springer.',
            "mla": 'Axler, Sheldon. Linear Algebra Done Right. 3rd ed., Springer, 2015.',
            "gbt": 'Axler S. Linear algebra done right[M]. 3rd ed. Springer, 2015.',
            "bibtex": '@book{axler2015linear, title={Linear Algebra Done Right}, author={Axler, Sheldon}, edition={3}, year={2015}, publisher={Springer}, doi={10.1007/978-3-319-11080-6}}',
        },
        "citations": 9000,
        "added_at": '2026-06-13',
    },
    {
        "id": 'principles-of-statistical-learning-2013',
        "type": 'book',
        "title": 'An Introduction to Statistical Learning',
        "authors": ['Gareth James', 'Daniela Witten', 'Trevor Hastie', 'Robert Tibshirani'],
        "year": 2013,
        "venue": 'Springer',
        "discipline": 'mathematics',
        "subdiscipline": 'statistics',
        "tags": ['统计学习', '机器学习', 'R', '教材'],
        "abstract": '《An Introduction to Statistical Learning》是统计学习领域的经典入门教材，介绍回归、分类、重抽样、线性模型选择、树方法、支持向量机等核心主题，并附有 R 代码。',
        "preview": '统计学习经典入门教材，覆盖回归、分类、重抽样与树方法，附 R 代码。',
        "download_url": 'https://www.statlearning.com/',
        "external_url": 'https://www.statlearning.com/',
        "doi": '10.1007/978-1-4614-7138-7',
        "citation": {
            "apa": 'James, G., Witten, D., Hastie, T., & Tibshirani, R. (2013). An introduction to statistical learning. Springer.',
            "mla": 'James, Gareth, et al. An Introduction to Statistical Learning. Springer, 2013.',
            "gbt": 'James G, Witten D, Hastie T, et al. An introduction to statistical learning[M]. Springer, 2013.',
            "bibtex": '@book{james2013introduction, title={An Introduction to Statistical Learning}, author={James, Gareth and Witten, Daniela and Hastie, Trevor and Tibshirani, Robert}, year={2013}, publisher={Springer}, doi={10.1007/978-1-4614-7138-7}}',
        },
        "citations": 35000,
        "added_at": '2026-06-13',
    },
    {
        "id": 'mnist-dataset-lecun-1998',
        "type": 'dataset',
        "title": 'The MNIST Database of Handwritten Digits',
        "authors": ['Yann LeCun', 'Corinna Cortes', 'Christopher J.C. Burges'],
        "year": 1998,
        "venue": 'AT&T Labs',
        "discipline": 'computer-science',
        "subdiscipline": 'computer-vision',
        "tags": ['手写数字', '数据集', '机器学习', '基准'],
        "abstract": 'MNIST 是一个包含 70,000 张 28×28 手写数字灰度图像的数据集，常被用作图像分类与机器学习算法的基准测试。',
        "preview": '手写数字识别基准数据集，包含 70,000 张 28×28 灰度图像。',
        "download_url": 'https://yann.lecun.com/exdb/mnist/',
        "external_url": 'https://yann.lecun.com/exdb/mnist/',
        "doi": None,
        "citation": {
            "apa": 'LeCun, Y., Cortes, C., & Burges, C. J. (1998). The MNIST database of handwritten digits. AT&T Labs.',
            "mla": 'LeCun, Yann, Corinna Cortes, and Christopher J.C. Burges. "The MNIST database of handwritten digits." AT&T Labs, 1998.',
            "gbt": 'LeCun Y, Cortes C, Burges C J C. The MNIST database of handwritten digits[J]. AT&T Labs, 1998.',
            "bibtex": '@article{lecun1998mnist, title={The MNIST database of handwritten digits}, author={LeCun, Yann and Cortes, Corinna and Burges, Christopher JC}, journal={AT&T Labs}, volume={2}, year={1998}}',
        },
        "citations": 18000,
        "added_at": '2026-06-13',
    },
    {
        "id": 'gravitational-waves-ligo-2016',
        "type": 'paper',
        "title": 'Observation of Gravitational Waves from a Binary Black Hole Merger',
        "authors": ['B.P. Abbott', 'R. Abbott', 'T.D. Abbott', 'M.R. Abernathy', 'F. Acernese', 'K. Ackley', 'C. Adams', 'T. Adams', 'P. Addesso', 'R.X. Adhikari'],
        "year": 2016,
        "venue": 'Physical Review Letters',
        "discipline": 'physics',
        "subdiscipline": 'astrophysics',
        "tags": ['引力波', '黑洞', 'LIGO', '天体物理'],
        "abstract": 'LIGO 与 Virgo 合作团队首次直接探测到双黑洞并合产生的引力波，开启了引力波天文学的新时代。',
        "preview": '首次直接探测到双黑洞并合引力波，开启引力波天文学新时代。',
        "download_url": 'https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.116.061102',
        "external_url": 'https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.061102',
        "doi": '10.1103/PhysRevLett.116.061102',
        "citation": {
            "apa": 'Abbott, B. P., et al. (2016). Observation of gravitational waves from a binary black hole merger. Physical Review Letters, 116(6), 061102.',
            "mla": 'Abbott, B. P., et al. "Observation of gravitational waves from a binary black hole merger." Physical Review Letters, vol. 116, no. 6, 2016, p. 061102.',
            "gbt": 'Abbott B P, Abbott R, Abbott T D, et al. Observation of gravitational waves from a binary black hole merger[J]. Physical Review Letters, 2016, 116(6): 061102.',
            "bibtex": '@article{abbott2016observation, title={Observation of gravitational waves from a binary black hole merger}, author={Abbott, Benjamin P and Abbott, Richard and Abbott, Thomas D and Abernathy, Matthew R and Acernese, Fausto and Ackley, Kendall and Adams, Carl and Adams, Thomas and Addesso, Paolo and Adhikari, Rana X and others}, journal={Physical Review Letters}, volume={116}, number={6}, pages={061102}, year={2016}, publisher={APS}}',
        },
        "citations": 22000,
        "added_at": '2026-06-14',
    },
    {
        "id": 'molecular-biology-of-the-cell-2014',
        "type": 'book',
        "title": 'Molecular Biology of the Cell',
        "authors": ['Bruce Alberts', 'Alexander Johnson', 'Julian Lewis', 'David Morgan', 'Martin Raff', 'Keith Roberts', 'Peter Walter'],
        "year": 2014,
        "venue": 'W.W. Norton & Company',
        "discipline": 'life-sciences',
        "subdiscipline": 'molecular-biology',
        "tags": ['细胞生物学', '生命科学', '教材', '分子生物学'],
        "abstract": '《Molecular Biology of the Cell》是生命科学领域最具影响力的细胞生物学教材之一，系统介绍细胞的结构、功能与分子机制。',
        "preview": '生命科学领域经典细胞生物学教材，系统介绍细胞结构与分子机制。',
        "download_url": None,
        "external_url": 'https://www.ncbi.nlm.nih.gov/books/NBK21054/',
        "doi": None,
        "citation": {
            "apa": 'Alberts, B., Johnson, A., Lewis, J., Morgan, D., Raff, M., Roberts, K., & Walter, P. (2014). Molecular biology of the cell (6th ed.). W.W. Norton & Company.',
            "mla": 'Alberts, Bruce, et al. Molecular Biology of the Cell. 6th ed., W.W. Norton & Company, 2014.',
            "gbt": 'Alberts B, Johnson A, Lewis J, et al. Molecular biology of the cell[M]. 6th ed. W.W. Norton & Company, 2014.',
            "bibtex": '@book{alberts2014molecular, title={Molecular Biology of the Cell}, author={Alberts, Bruce and Johnson, Alexander and Lewis, Julian and Morgan, David and Raff, Martin and Roberts, Keith and Walter, Peter}, edition={6}, year={2014}, publisher={W.W. Norton & Company}}',
        },
        "citations": 43000,
        "added_at": '2026-06-14',
    },
    {
        "id": 'python-data-science-handbook-2016',
        "type": 'book',
        "title": 'Python Data Science Handbook',
        "authors": ['Jake VanderPlas'],
        "year": 2016,
        "venue": "O'Reilly Media",
        "discipline": 'computer-science',
        "subdiscipline": 'data-science',
        "tags": ['Python', '数据科学', 'Jupyter', '教材'],
        "abstract": '《Python Data Science Handbook》详细介绍使用 Python 进行数据科学工作的核心工具栈，包括 NumPy、Pandas、Matplotlib 与 Scikit-Learn。',
        "preview": '使用 Python 进行数据科学的实用手册，覆盖 NumPy、Pandas、Matplotlib 与 Scikit-Learn。',
        "download_url": 'https://jakevdp.github.io/PythonDataScienceHandbook/',
        "external_url": 'https://jakevdp.github.io/PythonDataScienceHandbook/',
        "doi": None,
        "citation": {
            "apa": "VanderPlas, J. (2016). Python data science handbook. O'Reilly Media.",
            "mla": "VanderPlas, Jake. Python Data Science Handbook. O'Reilly Media, 2016.",
            "gbt": "VanderPlas J. Python data science handbook[M]. O'Reilly Media, 2016.",
            "bibtex": "@book{vanderplas2016python, title={Python Data Science Handbook}, author={VanderPlas, Jake}, year={2016}, publisher={O'Reilly Media}}",
        },
        "citations": 8500,
        "added_at": '2026-06-14',
    },
    {
        "id": 'bert-devlin-2019',
        "type": 'paper',
        "title": 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
        "authors": ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
        "year": 2019,
        "venue": 'NAACL-HLT 2019',
        "discipline": 'computer-science',
        "subdiscipline": 'natural-language-processing',
        "tags": ['BERT', '预训练', 'NLP', 'Transformer'],
        "abstract": 'BERT 通过掩码语言模型与下一句预测任务进行双向预训练，在多项自然语言理解基准上取得突破性进展。',
        "preview": '提出 BERT 双向预训练模型，推动 NLP 进入预训练微调范式。',
        "download_url": 'https://aclanthology.org/N19-1423.pdf',
        "external_url": 'https://aclanthology.org/N19-1423/',
        "doi": None,
        "citation": {
            "apa": 'Devlin, J., Chang, M. W., Lee, K., & Toutanova, K. (2019). BERT: Pre-training of deep bidirectional transformers for language understanding. Proceedings of NAACL-HLT.',
            "mla": 'Devlin, Jacob, et al. "BERT: Pre-training of deep bidirectional transformers for language understanding." Proceedings of NAACL-HLT, 2019, pp. 4171-4186.',
            "gbt": 'Devlin J, Chang M W, Lee K, et al. BERT: Pre-training of deep bidirectional transformers for language understanding[C]//Proceedings of NAACL-HLT. 2019: 4171-4186.',
            "bibtex": '@inproceedings{devlin2019bert, title={BERT: Pre-training of deep bidirectional transformers for language understanding}, author={Devlin, Jacob and Chang, Ming-Wei and Lee, Kenton and Toutanova, Kristina}, booktitle={Proceedings of NAACL-HLT}, pages={4171--4186}, year={2019}}',
        },
        "citations": 65000,
        "added_at": '2026-06-15',
    },
    {
        "id": 'kaggle-titanic-dataset',
        "type": 'dataset',
        "title": 'Titanic - Machine Learning from Disaster',
        "authors": ['Kaggle'],
        "year": 2012,
        "venue": 'Kaggle',
        "discipline": 'computer-science',
        "subdiscipline": 'data-science',
        "tags": ['数据竞赛', '分类', '入门', 'Kaggle'],
        "abstract": 'Titanic 数据集是数据科学入门最经典的数据集之一，包含乘客信息与生存标签，常用于练习分类与特征工程。',
        "preview": '数据科学入门经典竞赛数据集，用于练习分类与特征工程。',
        "download_url": 'https://www.kaggle.com/competitions/titanic/data',
        "external_url": 'https://www.kaggle.com/competitions/titanic',
        "doi": None,
        "citation": {
            "apa": 'Kaggle. (2012). Titanic: Machine learning from disaster. Kaggle Inc.',
            "mla": 'Kaggle. Titanic: Machine Learning from Disaster. Kaggle Inc., 2012.',
            "gbt": 'Kaggle. Titanic: Machine learning from disaster[DB/OL]. Kaggle Inc, 2012.',
            "bibtex": '@misc{kaggle2012titanic, title={Titanic: Machine Learning from Disaster}, author={Kaggle}, year={2012}, howpublished={\\url{https://www.kaggle.com/competitions/titanic}}}',
        },
        "citations": 3000,
        "added_at": '2026-06-15',
    },
    {
        "id": 'fastai-course-2022',
        "type": 'tutorial',
        "title": 'Practical Deep Learning for Coders',
        "authors": ['Jeremy Howard', 'Sylvain Gugger'],
        "year": 2022,
        "venue": 'fast.ai',
        "discipline": 'computer-science',
        "subdiscipline": 'machine-learning',
        "tags": ['深度学习', 'fastai', 'PyTorch', '课程'],
        "abstract": 'fast.ai 推出的面向程序员的实用深度学习课程，强调自上而下学习，结合 Jupyter Notebook 与真实项目实践。',
        "preview": '面向程序员的实用深度学习课程，强调自上而下学习与真实项目实践。',
        "download_url": 'https://course.fast.ai/',
        "external_url": 'https://course.fast.ai/',
        "doi": None,
        "citation": {
            "apa": 'Howard, J., & Gugger, S. (2022). Practical deep learning for coders. fast.ai.',
            "mla": 'Howard, Jeremy, and Sylvain Gugger. Practical Deep Learning for Coders. fast.ai, 2022.',
            "gbt": 'Howard J, Gugger S. Practical deep learning for coders[EB/OL]. fast.ai, 2022.',
            "bibtex": '@misc{howard2022practical, title={Practical Deep Learning for Coders}, author={Howard, Jeremy and Gugger, Sylvain}, year={2022}, howpublished={\\url{https://course.fast.ai/}}}',
        },
        "citations": 2500,
        "added_at": '2026-06-15',
    },
    {
        "id": 'origin-of-species-1859',
        "type": 'book',
        "title": 'On the Origin of Species',
        "authors": ['Charles Darwin'],
        "year": 1859,
        "venue": 'John Murray',
        "discipline": 'life-sciences',
        "subdiscipline": 'evolutionary-biology',
        "tags": ['进化论', '生物学', '经典', '自然选择'],
        "abstract": '《物种起源》是达尔文阐述进化论与自然选择学说的奠基之作，深刻改变了人类对生命多样性与起源的理解。',
        "preview": '达尔文进化论与自然选择学说的奠基之作。',
        "download_url": 'https://www.gutenberg.org/files/2009/2009-h/2009-h.htm',
        "external_url": 'https://www.gutenberg.org/ebooks/2009',
        "doi": None,
        "citation": {
            "apa": 'Darwin, C. (1859). On the origin of species. John Murray.',
            "mla": 'Darwin, Charles. On the Origin of Species. John Murray, 1859.',
            "gbt": 'Darwin C. On the origin of species[M]. John Murray, 1859.',
            "bibtex": '@book{darwin1859origin, title={On the Origin of Species}, author={Darwin, Charles}, year={1859}, publisher={John Murray}}',
        },
        "citations": 45000,
        "added_at": '2026-06-16',
    },
    {
        "id": 'wealth-of-nations-1776',
        "type": 'book',
        "title": 'The Wealth of Nations',
        "authors": ['Adam Smith'],
        "year": 1776,
        "venue": 'W. Strahan and T. Cadell',
        "discipline": 'social-sciences',
        "subdiscipline": 'economics',
        "tags": ['经济学', '古典经济学', '经典', '市场经济'],
        "abstract": '《国富论》是亚当·斯密的经典经济学著作，系统阐述了劳动分工、自由市场与看不见的手等核心经济学思想。',
        "preview": '古典经济学奠基之作，阐述劳动分工、自由市场与看不见的手。',
        "download_url": 'https://www.gutenberg.org/files/3300/3300-h/3300-h.htm',
        "external_url": 'https://www.gutenberg.org/ebooks/3300',
        "doi": None,
        "citation": {
            "apa": 'Smith, A. (1776). An inquiry into the nature and causes of the wealth of nations. W. Strahan and T. Cadell.',
            "mla": 'Smith, Adam. The Wealth of Nations. W. Strahan and T. Cadell, 1776.',
            "gbt": 'Smith A. An inquiry into the nature and causes of the wealth of nations[M]. W. Strahan and T. Cadell, 1776.',
            "bibtex": '@book{smith1776wealth, title={An Inquiry into the Nature and Causes of the Wealth of Nations}, author={Smith, Adam}, year={1776}, publisher={W. Strahan and T. Cadell}}',
        },
        "citations": 38000,
        "added_at": '2026-06-16',
    },
    {
        "id": 'general-relativity-einstein-1915',
        "type": 'paper',
        "title": 'The Field Equations of Gravitation',
        "authors": ['Albert Einstein'],
        "year": 1915,
        "venue": 'Sitzungsberichte der Preussischen Akademie der Wissenschaften',
        "discipline": 'physics',
        "subdiscipline": 'theoretical-physics',
        "tags": ['广义相对论', '引力场方程', '物理学', '经典'],
        "abstract": '爱因斯坦在这篇论文中提出了广义相对论的引力场方程，将引力描述为时空弯曲的几何效应。',
        "preview": '提出广义相对论引力场方程，将引力描述为时空弯曲。',
        "download_url": None,
        "external_url": 'https://einsteinpapers.press.princeton.edu/vol6-doc/261',
        "doi": None,
        "citation": {
            "apa": 'Einstein, A. (1915). The field equations of gravitation. Sitzungsberichte der Preussischen Akademie der Wissenschaften.',
            "mla": 'Einstein, Albert. "The field equations of gravitation." Sitzungsberichte der Preussischen Akademie der Wissenschaften, 1915.',
            "gbt": 'Einstein A. The field equations of gravitation[J]. Sitzungsberichte der Preussischen Akademie der Wissenschaften, 1915.',
            "bibtex": '@article{einstein1915field, title={The field equations of gravitation}, author={Einstein, Albert}, journal={Sitzungsberichte der Preussischen Akademie der Wissenschaften}, pages={844--847}, year={1915}}',
        },
        "citations": 12000,
        "added_at": '2026-06-16',
    },
    {
        "id": '3blue1brown-linear-algebra',
        "type": 'tutorial',
        "title": 'Essence of Linear Algebra',
        "authors": ['Grant Sanderson'],
        "year": 2016,
        "venue": '3Blue1Brown',
        "discipline": 'mathematics',
        "subdiscipline": 'linear-algebra',
        "tags": ['线性代数', '可视化', '课程', '入门'],
        "abstract": '3Blue1Brown 的《线性代数的本质》系列视频通过动画直观讲解向量、矩阵、线性变换、特征值等核心概念。',
        "preview": '通过动画直观讲解线性代数核心概念的经典视频系列。',
        "download_url": 'https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab',
        "external_url": 'https://www.3blue1brown.com/topics/linear-algebra',
        "doi": None,
        "citation": {
            "apa": 'Sanderson, G. (2016). Essence of linear algebra [Video series]. 3Blue1Brown.',
            "mla": 'Sanderson, Grant. Essence of Linear Algebra. 3Blue1Brown, 2016.',
            "gbt": 'Sanderson G. Essence of linear algebra[EB/OL]. 3Blue1Brown, 2016.',
            "bibtex": '@misc{sanderson2016essence, title={Essence of Linear Algebra}, author={Sanderson, Grant}, year={2016}, howpublished={\\url{https://www.3blue1brown.com/topics/linear-algebra}}}',
        },
        "citations": 5000,
        "added_at": '2026-06-17',
    },
    {
        "id": 'uc-irvine-ml-repository',
        "type": 'dataset',
        "title": 'UCI Machine Learning Repository',
        "authors": ['Dua, D. and Graff, C.'],
        "year": 2017,
        "venue": 'University of California, Irvine',
        "discipline": 'computer-science',
        "subdiscipline": 'machine-learning',
        "tags": ['数据集', '机器学习', 'UCI', ' benchmark'],
        "abstract": 'UCI Machine Learning Repository 是一个收集了数百个机器学习数据集的公开仓库，广泛用于算法评估与教学。',
        "preview": '数百个机器学习数据集公开仓库，广泛用于算法评估与教学。',
        "download_url": 'https://archive.ics.uci.edu/ml/index.php',
        "external_url": 'https://archive.ics.uci.edu/',
        "doi": None,
        "citation": {
            "apa": 'Dua, D., & Graff, C. (2017). UCI machine learning repository. University of California, Irvine.',
            "mla": 'Dua, Dheeru, and Casey Graff. UCI Machine Learning Repository. University of California, Irvine, 2017.',
            "gbt": 'Dua D, Graff C. UCI machine learning repository[DB/OL]. University of California, Irvine, 2017.',
            "bibtex": '@misc{dua2017uci, title={UCI Machine Learning Repository}, author={Dua, Dheeru and Graff, Casey}, year={2017}, howpublished={\\url{https://archive.ics.uci.edu/ml/}}, institution={University of California, Irvine, School of Information and Computer Sciences}}',
        },
        "citations": 6000,
        "added_at": '2026-06-17',
    },
    {
        "id": 'thinking-fast-and-slow-2011',
        "type": 'book',
        "title": 'Thinking, Fast and Slow',
        "authors": ['Daniel Kahneman'],
        "year": 2011,
        "venue": 'Farrar, Straus and Giroux',
        "discipline": 'social-sciences',
        "subdiscipline": 'psychology',
        "tags": ['心理学', '行为经济学', '认知偏差', '经典'],
        "abstract": '《思考，快与慢》总结了行为经济学与认知心理学的研究成果，介绍人类思维中快速直觉与缓慢理性两种系统。',
        "preview": '行为经济学经典，介绍人类思维的快思考与慢思考两种系统。',
        "download_url": None,
        "external_url": 'https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow',
        "doi": None,
        "citation": {
            "apa": 'Kahneman, D. (2011). Thinking, fast and slow. Farrar, Straus and Giroux.',
            "mla": 'Kahneman, Daniel. Thinking, Fast and Slow. Farrar, Straus and Giroux, 2011.',
            "gbt": 'Kahneman D. Thinking, fast and slow[M]. Farrar, Straus and Giroux, 2011.',
            "bibtex": '@book{kahneman2011thinking, title={Thinking, Fast and Slow}, author={Kahneman, Daniel}, year={2011}, publisher={Farrar, Straus and Giroux}}',
        },
        "citations": 28000,
        "added_at": '2026-06-17',
    },
    {
        "id": 'cell-atlas-human-protein-atlas',
        "type": 'dataset',
        "title": 'Human Protein Atlas',
        "authors": ['Mathias Uhlén', 'Linn Fagerberg', 'Björn M. Hallström', 'Cecilia Lindskog', 'Per Oksvold', 'Albin Fredlund', 'Martin Sivertsson', 'Åsa Sivertsson', 'Jacob Odeberg', 'Muhammad Arif'],
        "year": 2015,
        "venue": 'Science',
        "discipline": 'life-sciences',
        "subdiscipline": 'proteomics',
        "tags": ['蛋白质', '人类蛋白质图谱', '生命科学', '数据集'],
        "abstract": 'Human Protein Atlas 项目绘制了人体细胞、组织和器官中蛋白质表达与定位的综合图谱，是系统生物学研究的重要资源。',
        "preview": '人体蛋白质表达与定位综合图谱，系统生物学研究重要资源。',
        "download_url": 'https://www.proteinatlas.org/download',
        "external_url": 'https://www.proteinatlas.org/',
        "doi": '10.1126/science.1260419',
        "citation": {
            "apa": 'Uhlén, M., et al. (2015). Tissue-based map of the human proteome. Science, 347(6220), 1260419.',
            "mla": 'Uhlén, Mathias, et al. "Tissue-based map of the human proteome." Science, vol. 347, no. 6220, 2015, p. 1260419.',
            "gbt": 'Uhlén M, Fagerberg L, Hallström B M, et al. Tissue-based map of the human proteome[J]. Science, 2015, 347(6220): 1260419.',
            "bibtex": '@article{uhlen2015tissue, title={Tissue-based map of the human proteome}, author={Uhl{\\\'e}n, Mathias and Fagerberg, Linn and Hallstr{\\"o}m, Bj{\\"o}rn M and Lindskog, Cecilia and Oksvold, Per and Mardinoglu, Adil and Sivertsson, Asa and Kampf, Caroline and Sj{\\"o}stedt, Evelina and Asplund, Anna and others}, journal={Science}, volume={347}, number={6220}, pages={1260419}, year={2015}, publisher={American Association for the Advancement of Science}}',
        },
        "citations": 9500,
        "added_at": '2026-06-17',
    },
    {
        "id": 'republic-plato-375-bc',
        "type": 'book',
        "title": '理想国',
        "authors": ['Plato'],
        "year": -375,
        "venue": '古希腊哲学对话录',
        "discipline": 'humanities',
        "subdiscipline": 'philosophy',
        "tags": ['政治哲学“, ”正义“, ”乌托邦“, ”古希腊哲学'],
        "abstract": '柏拉图以苏格拉底为主角，探讨正义、理想城邦、灵魂三分与哲人王统治的经典对话录，奠定了西方政治哲学与形而上学的基石。',
        "preview": '西方政治哲学奠基之作，借苏格拉底之口追问“什么是正义”并构想理想城邦。',
        "download_url": None,
        "external_url": 'https://www.gutenberg.org/ebooks/1497',
        "doi": None,
        "citation": {
            "apa": 'Plato. (n.d.). The Republic.',
            "mla": 'Plato. The Republic.',
            "gbt": 'Plato. 理想国[M].',
            "bibtex": '@book{plato_republic, title={The Republic}, author={Plato}}',
        },
        "citations": 85000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'nicomachean-ethics-aristotle',
        "type": 'book',
        "title": '尼各马可伦理学',
        "authors": ['Aristotle'],
        "year": -350,
        "venue": '古希腊伦理学经典',
        "discipline": 'humanities',
        "subdiscipline": 'philosophy',
        "tags": ['伦理学“, ”德性“, ”幸福“, ”实践智慧'],
        "abstract": '亚里士多德系统阐述德性伦理学，提出“幸福是实现灵魂合乎德性的活动”，并深入讨论勇敢、节制、正义、友谊与沉思生活。',
        "preview": '亚里士多德德性伦理学的核心文本，探讨幸福、德性与良好生活的本质。',
        "download_url": None,
        "external_url": 'https://www.gutenberg.org/ebooks/8438',
        "doi": None,
        "citation": {
            "apa": 'Aristotle. (n.d.). Nicomachean Ethics.',
            "mla": 'Aristotle. Nicomachean Ethics.',
            "gbt": 'Aristotle. 尼各马可伦理学[M].',
            "bibtex": '@book{aristotle_ethics, title={Nicomachean Ethics}, author={Aristotle}}',
        },
        "citations": 62000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'history-of-the-peloponnesian-war-thucydides',
        "type": 'book',
        "title": '伯罗奔尼撒战争史',
        "authors": ['Thucydides'],
        "year": -400,
        "venue": '古希腊史学经典',
        "discipline": 'humanities',
        "subdiscipline": 'history',
        "tags": ['古希腊史“, ”战争史“, ”国际关系“, ”修昔底德陷阱'],
        "abstract": '修昔底德以亲历者身份记述雅典与斯巴达之间的伯罗奔尼撒战争，被誉为西方政治现实主义与国际关系理论的源头之一。',
        "preview": '西方史学与政治现实主义传统的奠基之作，记录雅典与斯巴达的世纪战争。',
        "download_url": None,
        "external_url": 'https://www.gutenberg.org/ebooks/7142',
        "doi": None,
        "citation": {
            "apa": 'Thucydides. (n.d.). History of the Peloponnesian War.',
            "mla": 'Thucydides. History of the Peloponnesian War.',
            "gbt": 'Thucydides. 伯罗奔尼撒战争史[M].',
            "bibtex": '@book{thucydides_war, title={History of the Peloponnesian War}, author={Thucydides}}',
        },
        "citations": 45000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'the-open-society-and-its-enemies-popper-1945',
        "type": 'book',
        "title": '开放社会及其敌人',
        "authors": ['Karl Popper'],
        "year": 1945,
        "venue": 'Routledge',
        "discipline": 'humanities',
        "subdiscipline": 'philosophy',
        "tags": ['政治哲学“, ”开放社会“, ”历史决定论“, ”批判理性主义'],
        "abstract": '波普尔批判柏拉图、黑格尔与马克思的历史决定论，捍卫开放社会、民主制度与批判理性主义，对二十世纪政治哲学影响深远。',
        "preview": '波普尔为开放社会辩护，批判历史决定论与极权主义思想根源。',
        "download_url": None,
        "external_url": 'https://archive.org/details/opensocietyandit01popp',
        "doi": None,
        "citation": {
            "apa": 'Popper, K. (1945). The Open Society and Its Enemies. Routledge.',
            "mla": 'Popper, Karl. The Open Society and Its Enemies. Routledge, 1945.',
            "gbt": 'Popper K. 开放社会及其敌人[M]. Routledge, 1945.',
            "bibtex": '@book{popper1945open, title={The Open Society and Its Enemies}, author={Popper, Karl}, year={1945}, publisher={Routledge}}',
        },
        "citations": 38000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'the-waste-land-eliot-1922',
        "type": 'paper',
        "title": '荒原',
        "authors": ['T. S. Eliot'],
        "year": 1922,
        "venue": 'The Criterion',
        "discipline": 'humanities',
        "subdiscipline": 'literature',
        "tags": ['现代主义诗歌“, ”艾略特“, ”文学批评“, ”英美文学'],
        "abstract": 'T. S. 艾略特的长诗《荒原》以破碎的意象与多语言引文描绘战后西方文明的精神荒芜，被公认为现代主义诗歌的里程碑。',
        "preview": '现代主义诗歌里程碑，以碎片化的意象呈现战后文明的荒芜与救赎渴望。',
        "download_url": None,
        "external_url": 'https://www.bartleby.com/201/1.html',
        "doi": None,
        "citation": {
            "apa": 'Eliot, T. S. (1922). The Waste Land. The Criterion.',
            "mla": 'Eliot, T. S. “The Waste Land.” The Criterion, 1922.',
            "gbt": 'Eliot T S. 荒原[J]. The Criterion, 1922.',
            "bibtex": '@article{eliot1922waste, title={The Waste Land}, author={Eliot, T. S.}, journal={The Criterion}, year={1922}}',
        },
        "citations": 22000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'art-history-janson-1962',
        "type": 'book',
        "title": '艺术史',
        "authors": ['H. W. Janson', 'Anthony F. Janson'],
        "year": 1962,
        "venue": 'Harry N. Abrams',
        "discipline": 'humanities',
        "subdiscipline": 'art-history',
        "tags": ['艺术史“, ”视觉艺术“, ”西方艺术“, ”教材'],
        "abstract": '《艺术史》是西方艺术史领域最广泛使用的教材之一，系统梳理从史前艺术到现代艺术的风格演变、社会语境与关键作品。',
        "preview": '西方艺术史经典教材，贯通史前至现代的艺术风格与社会语境。',
        "download_url": None,
        "external_url": 'https://www.abramsbooks.com/product/art-history_9780134035835/',
        "doi": None,
        "citation": {
            "apa": 'Janson, H. W., & Janson, A. F. (1962). History of Art. Harry N. Abrams.',
            "mla": 'Janson, H. W., and Anthony F. Janson. History of Art. Harry N. Abrams, 1962.',
            "gbt": 'Janson H W, Janson A F. 艺术史[M]. Harry N. Abrams, 1962.',
            "bibtex": '@book{janson1962history, title={History of Art}, author={Janson, H. W. and Janson, Anthony F.}, year={1962}, publisher={Harry N. Abrams}}',
        },
        "citations": 15000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'the-general-theory-keynes-1936',
        "type": 'book',
        "title": '就业、利息和货币通论',
        "authors": ['John Maynard Keynes'],
        "year": 1936,
        "venue": 'Macmillan',
        "discipline": 'social-sciences',
        "subdiscipline": 'economics',
        "tags": ['宏观经济学“, ”凯恩斯主义“, ”有效需求“, ”失业'],
        "abstract": '凯恩斯在《通论》中挑战古典经济学，提出有效需求不足导致失业，主张政府通过财政与货币政策干预经济，奠定现代宏观经济学基础。',
        "preview": '现代宏观经济学奠基之作，提出有效需求理论与政府干预经济的理论基础。',
        "download_url": None,
        "external_url": 'https://archive.org/details/in.ernet.dli.2015.499719',
        "doi": None,
        "citation": {
            "apa": 'Keynes, J. M. (1936). The General Theory of Employment, Interest, and Money. Macmillan.',
            "mla": 'Keynes, John Maynard. The General Theory of Employment, Interest, and Money. Macmillan, 1936.',
            "gbt": 'Keynes J M. 就业、利息和货币通论[M]. Macmillan, 1936.',
            "bibtex": '@book{keynes1936general, title={The General Theory of Employment, Interest, and Money}, author={Keynes, John Maynard}, year={1936}, publisher={Macmillan}}',
        },
        "citations": 95000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'capital-marx-1867',
        "type": 'book',
        "title": '资本论（第一卷）',
        "authors": ['Karl Marx'],
        "year": 1867,
        "venue": 'Verlag von Otto Meisner',
        "discipline": 'social-sciences',
        "subdiscipline": 'economics',
        "tags": ['政治经济学“, ”马克思主义“, ”剩余价值“, ”资本主义批判'],
        "abstract": '马克思系统分析资本主义生产方式，揭示商品二重性、剩余价值来源与资本积累规律，对经济学、社会学与政治学产生深远影响。',
        "preview": '马克思剖析资本主义生产方式的核心著作，揭示剩余价值与资本积累机制。',
        "download_url": None,
        "external_url": 'https://www.marxists.org/archive/marx/works/1867-c1/',
        "doi": None,
        "citation": {
            "apa": 'Marx, K. (1867). Capital: A Critique of Political Economy (Vol. 1). Verlag von Otto Meisner.',
            "mla": 'Marx, Karl. Capital: A Critique of Political Economy. Vol. 1, Verlag von Otto Meisner, 1867.',
            "gbt": 'Marx K. 资本论（第一卷）[M]. Verlag von Otto Meisner, 1867.',
            "bibtex": '@book{marx1867capital, title={Capital: A Critique of Political Economy}, author={Marx, Karl}, volume={1}, year={1867}, publisher={Verlag von Otto Meisner}}',
        },
        "citations": 88000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'the-interpretation-of-dreams-freud-1899',
        "type": 'book',
        "title": '梦的解析',
        "authors": ['Sigmund Freud'],
        "year": 1899,
        "venue": 'Franz Deuticke',
        "discipline": 'social-sciences',
        "subdiscipline": 'psychology',
        "tags": ['精神分析“, ”潜意识“, ”梦“, ”心理学'],
        "abstract": '弗洛伊德在《梦的解析》中提出梦是通往潜意识的皇家大道，系统阐述凝缩、移置、象征与二次修饰等梦的运作机制。',
        "preview": '精神分析学奠基之作，提出梦是愿望满足与通往潜意识的途径。',
        "download_url": None,
        "external_url": 'https://www.gutenberg.org/ebooks/66048',
        "doi": None,
        "citation": {
            "apa": 'Freud, S. (1899). The Interpretation of Dreams. Franz Deuticke.',
            "mla": 'Freud, Sigmund. The Interpretation of Dreams. Franz Deuticke, 1899.',
            "gbt": 'Freud S. 梦的解析[M]. Franz Deuticke, 1899.',
            "bibtex": '@book{freud1899dreams, title={The Interpretation of Dreams}, author={Freud, Sigmund}, year={1899}, publisher={Franz Deuticke}}',
        },
        "citations": 75000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'cognitive-therapy-depression-beck-1979',
        "type": 'book',
        "title": '抑郁症的认知治疗',
        "authors": ['Aaron T. Beck'],
        "year": 1979,
        "venue": 'Guilford Press',
        "discipline": 'social-sciences',
        "subdiscipline": 'psychology',
        "tags": ['认知行为疗法“, ”抑郁症“, ”心理治疗“, ”临床心理学'],
        "abstract": '贝克提出认知治疗模型，认为抑郁源于负性自动思维与认知三联征（对自己、世界、未来的消极看法），并发展出系统的治疗技术。',
        "preview": '认知行为疗法奠基性临床手册，为抑郁症治疗提供系统的认知干预框架。',
        "download_url": None,
        "external_url": 'https://guilford.com/books/Cognitive-Therapy-of-Depression/Aaron-Beck/9780898629194',
        "doi": None,
        "citation": {
            "apa": 'Beck, A. T. (1979). Cognitive Therapy of Depression. Guilford Press.',
            "mla": 'Beck, Aaron T. Cognitive Therapy of Depression. Guilford Press, 1979.',
            "gbt": 'Beck A T. 抑郁症的认知治疗[M]. Guilford Press, 1979.',
            "bibtex": '@book{beck1979cognitive, title={Cognitive Therapy of Depression}, author={Beck, Aaron T.}, year={1979}, publisher={Guilford Press}}',
        },
        "citations": 54000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'the-division-of-labor-durkheim-1893',
        "type": 'book',
        "title": '社会分工论',
        "authors": ['Émile Durkheim'],
        "year": 1893,
        "venue": 'Félix Alcan',
        "discipline": 'social-sciences',
        "subdiscipline": 'sociology',
        "tags": ['社会学“, ”社会分工“, ”有机团结“, ”失范'],
        "abstract": '涂尔干区分机械团结与有机团结，论证社会分工如何整合现代社会，并引入“失范”概念解释社会转型期的规范缺失。',
        "preview": '社会学经典，提出机械团结与有机团结的区分，奠定现代社会分工理论。',
        "download_url": None,
        "external_url": 'https://archive.org/details/divisionoflabour00durk',
        "doi": None,
        "citation": {
            "apa": 'Durkheim, É. (1893). The Division of Labor in Society. Félix Alcan.',
            "mla": 'Durkheim, Émile. The Division of Labor in Society. Félix Alcan, 1893.',
            "gbt": 'Durkheim É. 社会分工论[M]. Félix Alcan, 1893.',
            "bibtex": "@book{durkheim1893division, title={The Division of Labor in Society}, author={Durkheim, {\\'E}mile}, year={1893}, publisher={F\\'elix Alcan}}",
        },
        "citations": 42000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'the-protestant-ethic-weber-1905',
        "type": 'book',
        "title": '新教伦理与资本主义精神',
        "authors": ['Max Weber'],
        "year": 1905,
        "venue": 'Archiv für Sozialwissenschaft und Sozialpolitik',
        "discipline": 'social-sciences',
        "subdiscipline": 'sociology',
        "tags": ['社会学“, ”宗教社会学“, ”资本主义“, ”现代性'],
        "abstract": '韦伯探讨加尔文宗新教伦理如何催生现代资本主义精神，强调文化观念对经济行为的塑造作用，奠定宗教社会学基础。',
        "preview": '宗教社会学经典，论证新教伦理与现代资本主义精神之间的亲和关系。',
        "download_url": None,
        "external_url": 'https://archive.org/details/protestantethic00webe',
        "doi": None,
        "citation": {
            "apa": 'Weber, M. (1905). The Protestant Ethic and the Spirit of Capitalism. Archiv für Sozialwissenschaft und Sozialpolitik.',
            "mla": 'Weber, Max. “The Protestant Ethic and the Spirit of Capitalism.” Archiv für Sozialwissenschaft und Sozialpolitik, 1905.',
            "gbt": 'Weber M. 新教伦理与资本主义精神[J]. Archiv für Sozialwissenschaft und Sozialpolitik, 1905.',
            "bibtex": '@article{weber1905protestant, title={The Protestant Ethic and the Spirit of Capitalism}, author={Weber, Max}, journal={Archiv f{\\"u}r Sozialwissenschaft und Sozialpolitik}, year={1905}}',
        },
        "citations": 68000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'political-order-oligarchies-michels-1911',
        "type": 'book',
        "title": '寡头统治铁律：现代民主制度中的政党社会学',
        "authors": ['Robert Michels'],
        "year": 1911,
        "venue": 'Klinkhardt',
        "discipline": 'social-sciences',
        "subdiscipline": 'political-science',
        "tags": ['政治学“, ”政党社会学“, ”寡头统治“, ”民主理论'],
        "abstract": '米歇尔斯提出“寡头统治铁律”，认为大型组织由于技术分工与领导专业化，必然趋向寡头化，对民主理论与实践提出深刻挑战。',
        "preview": '政党社会学经典，提出“寡头统治铁律”，分析组织与民主的张力。',
        "download_url": None,
        "external_url": 'https://archive.org/details/politicalparties00mich',
        "doi": None,
        "citation": {
            "apa": 'Michels, R. (1911). Political Parties: A Sociological Study of the Oligarchical Tendencies of Modern Democracy. Klinkhardt.',
            "mla": 'Michels, Robert. Political Parties: A Sociological Study of the Oligarchical Tendencies of Modern Democracy. Klinkhardt, 1911.',
            "gbt": 'Michels R. 寡头统治铁律：现代民主制度中的政党社会学[M]. Klinkhardt, 1911.',
            "bibtex": '@book{michels1911parties, title={Political Parties: A Sociological Study of the Oligarchical Tendencies of Modern Democracy}, author={Michels, Robert}, year={1911}, publisher={Klinkhardt}}',
        },
        "citations": 25000,
        "added_at": '2026-06-21',
    },
    {
        "id": 'world-values-survey-dataset',
        "type": 'dataset',
        "title": 'World Values Survey',
        "authors": ['World Values Survey Association'],
        "year": 2022,
        "venue": 'Open Social Science Data Repository',
        "discipline": 'social-sciences',
        "subdiscipline": 'social-research',
        "tags": ['调查数据“, ”价值观“, ”跨国比较“, ”社会科学数据'],
        "abstract": '世界价值观调查是全球最大的跨国社会态度与价值观重复横截面调查，涵盖民主、性别、宗教、幸福、信任等议题，开放下载用于学术研究。',
        "preview": '全球最大跨国价值观与社会态度调查数据集，支持经济学、社会学与政治学的比较研究。',
        "download_url": 'https://www.worldvaluessurvey.org/WVSDocumentationWV7.jsp',
        "external_url": 'https://www.worldvaluessurvey.org/',
        "doi": None,
        "citation": {
            "apa": 'World Values Survey Association. (2022). World Values Survey.',
            "mla": 'World Values Survey Association. World Values Survey. 2022.',
            "gbt": 'World Values Survey Association. World Values Survey[DB/OL]. 2022.',
            "bibtex": '@misc{wvs2022, title={World Values Survey}, author={World Values Survey Association}, year={2022}}',
        },
        "citations": 18000,
        "added_at": '2026-06-21',
    },
]

async def seed_resources(session: AsyncSession) -> None:
    for item in SEED_DATA:
        result = await session.execute(select(Resource).where(Resource.id == item["id"]))
        if result.scalar_one_or_none():
            print(f"Skipping existing resource: {item['id']}")
            continue

        resource = Resource(**item)
        session.add(resource)
        print(f"Adding resource: {item['id']}")

    await session.commit()


async def main() -> None:
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        await seed_resources(session)


if __name__ == "__main__":
    asyncio.run(main())
